// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyB3K3q4WpTwlztv5FU-N9G_8PaJYG6GMJY",
    authDomain: "songextractor-1010.firebaseapp.com",
    projectId: "songextractor-1010",
    storageBucket: "songextractor-1010.appspot.com",
    messagingSenderId: "128888242323",
    appId: "1:128888242323:web:59003ba9433794eb76cd66",
    measurementId: "G-9XDT9XGYDW"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0Z2N0rc_A_HAAfUrGPI_H95a1bxzF2zg',
    appId: '1:128888242323:android:4cba7449aaf3b3c176cd66',
    messagingSenderId: '128888242323',
    projectId: 'songextractor-1010',
    storageBucket: 'songextractor-1010.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZrdUM6a3ZoTYc7W0yOuXcURb_e0rjNZQ',
    appId: '1:128888242323:ios:3dadca1456b5564d76cd66',
    messagingSenderId: '128888242323',
    projectId: 'songextractor-1010',
    storageBucket: 'songextractor-1010.firebasestorage.app',
    iosBundleId: 'com.example.songextractor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZrdUM6a3ZoTYc7W0yOuXcURb_e0rjNZQ',
    appId: '1:128888242323:ios:3dadca1456b5564d76cd66',
    messagingSenderId: '128888242323',
    projectId: 'songextractor-1010',
    storageBucket: 'songextractor-1010.firebasestorage.app',
    iosBundleId: 'com.example.songextractor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3K3q4WpTwlztv5FU-N9G_8PaJYG6GMJY',
    appId: '1:128888242323:web:fe03a660ac7735f576cd66',
    messagingSenderId: '128888242323',
    projectId: 'songextractor-1010',
    authDomain: 'songextractor-1010.firebaseapp.com',
    storageBucket: 'songextractor-1010.firebasestorage.app',
    measurementId: 'G-LLZVBFZJLK',
  );

}